// lib/mock-products.ts
import type { BoardStyleLabel, Product, ProductCategory } from "./types";

function boardStyleLabel(style: "cruiser" | "surfskate" | "longboard"): BoardStyleLabel {
  if (style === "surfskate") return "Surfskate";
  if (style === "longboard") return "Longboard";
  return "Cruiser";
}

export const products: Product[] = [
  {
    id: "board-coastline-cruiser-001",
    handle: "coastline-cruiser-jarrah-marri",
    title: "Coastline Cruiser 001",
    price: 950,
    currency: "AUD",
    category: "Reclaimed cruisers",
    productType: "board",
    description:
      "A compact one-of-a-kind cruiser shaped for Western Australian coastal paths, short carves, and everyday local rides. Built from reclaimed jarrah and marri pallet hardwood with visible grain contrast.",
    material: "Recycled jarrah and marri hardwood pallet timber",
    dimensions: "32 in × 9 in × 0.75 in / approx. 81.3 cm × 22.9 cm × 1.9 cm",
    colours: ["Jarrah red-brown", "Marri honey grain", "Clear sealed timber"],
    images: [],
    boardStyles: [boardStyleLabel("cruiser")],
    inStock: true,
    availabilityStatus: "available",
    timberSpecies: ["Jarrah", "Marri"],
    boardStyle: "cruiser",
    boardShape: "Kicktail cruiser",
    boardDimensions: {
      display: "32 in × 9 in × 0.75 in / approx. 81.3 cm × 22.9 cm × 1.9 cm",
      lengthInches: 32,
      widthInches: 9,
      thicknessInches: 0.75,
      lengthCm: 81.3,
      widthCm: 22.9,
      thicknessCm: 1.9,
      wheelbaseInches: 17.25,
    },
    specs: [
      { label: "Style", value: "Cruiser" },
      { label: "Shape", value: "Kicktail cruiser" },
      { label: "Dimensions", value: "32 in × 9 in × 0.75 in" },
      { label: "Approx. wheelbase", value: "17.25 in" },
      { label: "Timber", value: "Recycled jarrah / marri" },
      { label: "Pickup", value: "Western Australia local pickup only" },
    ],
    galleryNotes:
      "Jarrah and marri contrast gives this compact cruiser a warm WA hardwood palette with a practical everyday stance.",
    designFamily: "Cruiser",
    productionNotes: "One-off mock board for Phase 2 catalogue structure.",
  },
  {
    id: "board-reef-runner-002",
    handle: "reef-runner-karri-wandoo-surfskate",
    title: "Reef Runner 002",
    price: 995,
    currency: "AUD",
    category: "Surfskate deckz",
    productType: "board",
    description:
      "A longer surfskate-influenced deck for flowing carves and beach-break training. Reclaimed karri and wandoo strips give the board a dense hardwood feel and a clean coastal line.",
    material: "Recycled karri and wandoo hardwood pallet timber",
    dimensions: "38 in × 10 in × 0.75 in / approx. 96.5 cm × 25.4 cm × 1.9 cm",
    colours: ["Karri amber", "Wandoo pale gold", "Clear sealed timber"],
    images: [],
    boardStyles: [boardStyleLabel("surfskate")],
    inStock: true,
    availabilityStatus: "available",
    timberSpecies: ["Karri", "Wandoo"],
    boardStyle: "surfskate",
    boardShape: "Long surfskate cruiser",
    boardDimensions: {
      display: "38 in × 10 in × 0.75 in / approx. 96.5 cm × 25.4 cm × 1.9 cm",
      lengthInches: 38,
      widthInches: 10,
      thicknessInches: 0.75,
      lengthCm: 96.5,
      widthCm: 25.4,
      thicknessCm: 1.9,
      wheelbaseInches: 21.5,
    },
    specs: [
      { label: "Style", value: "Surfskate / longboard" },
      { label: "Shape", value: "Long surfskate cruiser" },
      { label: "Dimensions", value: "38 in × 10 in × 0.75 in" },
      { label: "Approx. wheelbase", value: "21.5 in" },
      { label: "Timber", value: "Recycled karri / wandoo" },
      { label: "Pickup", value: "Western Australia local pickup only" },
    ],
    galleryNotes:
      "Built around longer flowing lines with enough platform width for surfskate-inspired carving and display-worthy timber grain.",
    designFamily: "Surfskate",
    productionNotes: "One-off mock board for Phase 2 catalogue structure.",
  },
  {
    id: "board-sunset-pintail-003",
    handle: "sunset-pintail-sheoak-jarrah",
    title: "Sunset Pintail 003",
    price: 900,
    currency: "AUD",
    category: "Reclaimed cruisers",
    productType: "board",
    description:
      "A sold one-off pintail cruiser built from recycled sheoak and jarrah. Kept in the gallery as evidence of the Plankz craft language: reclaimed timber, coastal flow, and no duplicate builds.",
    material: "Recycled sheoak and jarrah hardwood pallet timber",
    dimensions: "36 in × 9.5 in × 0.75 in / approx. 91.4 cm × 24.1 cm × 1.9 cm",
    colours: ["Sheoak orange grain", "Jarrah red-brown", "Clear sealed timber"],
    images: [],
    boardStyles: [boardStyleLabel("cruiser")],
    inStock: false,
    availabilityStatus: "sold",
    timberSpecies: ["Sheoak", "Jarrah"],
    boardStyle: "cruiser",
    boardShape: "Pintail cruiser",
    boardDimensions: {
      display: "36 in × 9.5 in × 0.75 in / approx. 91.4 cm × 24.1 cm × 1.9 cm",
      lengthInches: 36,
      widthInches: 9.5,
      thicknessInches: 0.75,
      lengthCm: 91.4,
      widthCm: 24.1,
      thicknessCm: 1.9,
      wheelbaseInches: 20,
    },
    specs: [
      { label: "Style", value: "Pintail cruiser" },
      { label: "Shape", value: "Directional pintail" },
      { label: "Dimensions", value: "36 in × 9.5 in × 0.75 in" },
      { label: "Approx. wheelbase", value: "20 in" },
      { label: "Timber", value: "Recycled sheoak / jarrah" },
      { label: "Status", value: "Sold — archived to gallery" },
    ],
    galleryNotes:
      "A finished one-off reference piece showing warm sheoak grain against deeper jarrah strips in a relaxed pintail cruiser outline.",
    designFamily: "Cruiser",
    productionNotes: "Sold mock board retained for Phase 2 gallery behaviour.",
  },
  {
    id: "merch-og-plankz-logo-tee",
    handle: "og-plankz-logo-tee",
    title: "OG Plankz Logo Tee",
    price: 45,
    currency: "AUD",
    category: "Merch",
    productType: "merch",
    description:
      "A clean PLANKZ DECKZ logo tee for the coastal recycled-timber crew. Repeatable merch item with selectable apparel sizing.",
    material: "Cotton tee placeholder",
    dimensions: "Apparel sizing S / M / L / XL",
    colours: ["Washed white", "Teal logo", "Coral detail"],
    images: [],
    boardStyles: [],
    inStock: true,
    merchKind: "tee",
    sizes: ["S", "M", "L", "XL"],
    sizeRequired: true,
    fitNotes: "Regular adult fit. Select S, M, L, or XL before adding to cart.",
    designFamily: "Merch",
  },
  {
    id: "merch-plankz-flanno",
    handle: "plankz-flanno",
    title: "Plankz Flanno",
    price: 85,
    currency: "AUD",
    category: "Merch",
    productType: "merch",
    description:
      "A flannelette jumper for cool coastal mornings, shed work, and post-skate hangs. Repeatable merch item with selectable apparel sizing.",
    material: "Flannelette jumper placeholder",
    dimensions: "Apparel sizing S / M / L / XL",
    colours: ["Weathered grey", "Warm timber check", "Teal brand hit"],
    images: [],
    boardStyles: [],
    inStock: true,
    merchKind: "flanno",
    sizes: ["S", "M", "L", "XL"],
    sizeRequired: true,
    fitNotes: "Relaxed outer-layer fit. Select S, M, L, or XL before adding to cart.",
    designFamily: "Merch",
  },
  {
    id: "merch-plankz-sticker-pack",
    handle: "plankz-sticker-pack",
    title: "Sticker Pack",
    price: 15,
    currency: "AUD",
    category: "Merch",
    productType: "merch",
    description:
      "A small pack of PLANKZ DECKZ logo and deck-culture stickers for boards, toolboxes, eskies, and workshop surfaces.",
    material: "Vinyl sticker placeholder",
    dimensions: "Mixed sticker pack / one size",
    colours: ["Teal", "Coral", "Gold", "Weathered grey"],
    images: [],
    boardStyles: [],
    inStock: true,
    merchKind: "sticker_pack",
    sizes: ["One size"],
    sizeRequired: false,
    fitNotes: "One-size sticker pack. No apparel sizing required.",
    designFamily: "Merch",
  },
];

export function getProductByHandle(handle: string): Product | undefined {
  return products.find((product) => product.handle === handle);
}

export const categories: ProductCategory[] = ["One-of-a-kind boards", "Merch"];
